// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ4eXaWt2X1XjBzogJDIA3RnhMK1HlB98',
    appId: '1:55169145493:web:5ca8a1bca3986abc62199c',
    messagingSenderId: '55169145493',
    projectId: 'template-aa930',
    authDomain: 'template-aa930.firebaseapp.com',
    storageBucket: 'template-aa930.firebasestorage.app',
    measurementId: 'G-MTRJPDSHPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxPTr-CbpevPEM2DvYSS5AIC8kLavPdvw',
    appId: '1:55169145493:android:711ad7fc0b10f8d662199c',
    messagingSenderId: '55169145493',
    projectId: 'template-aa930',
    storageBucket: 'template-aa930.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuaAzbYTRytO7xDPcnfKq7aaA6MN0X92E',
    appId: '1:55169145493:ios:530401ca69073ce262199c',
    messagingSenderId: '55169145493',
    projectId: 'template-aa930',
    storageBucket: 'template-aa930.firebasestorage.app',
    iosBundleId: 'com.example.template',
  );
}
