// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

    static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu7tAlV3sDEeTFAlxUWbJH4PXPSB65dZk',
    appId: '1:628004937987:android:767439c0fbf8498fce0936',
    messagingSenderId: '628004937987',
    projectId: 'template-dev-e550f',
    storageBucket: 'template-dev-e550f.firebasestorage.app',
  );

    static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-97GGriHFGLXKDRbuzzPZ6E7_dcJhqFg',
    appId: '1:628004937987:ios:beb956f8ad715415ce0936',
    messagingSenderId: '628004937987',
    projectId: 'template-dev-e550f',
    storageBucket: 'template-dev-e550f.firebasestorage.app',
    iosBundleId: 'com.tefter.tefterapp.dev',
  );

}
